on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_ENGINE: postgresql+psycopg2://${POSTGRES_USER?}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}
      DATABASE_POOL_SIZE: 10
      APP_URL: http://app:8002/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose build
      - run: docker compose up -d
      - run: sleep 15
      - run: pytest tests --junit-xml=test-results.xml
        env:
          APP_URL: http://127.0.0.1:8002

      - run: docker compose logs app
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results